# Generated by Django 6.0.4 on 2026-06-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrating",
            name="review",
        ),
    ]
