# Generated by Django 6.0.4 on 2026-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
