# Generated by Django 6.0.4 on 2026-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
